# Generated by Django 6.1.1 on 2026-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20)),
                ('usuario', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Em atendimento', 'Em atendimento'), ('Resolvido', 'Resolvido'), ('Cancelado', 'Cancelado')], default='Novo', max_length=30)),
                ('id_glpi', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('area_solicitante', models.CharField(max_length=100)),
                ('descricao_problema', models.TextField()),
                ('objetivo', models.TextField()),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta')], default='Media', max_length=20)),
                ('beneficio_esperado', models.TextField(blank=True, null=True)),
                ('prazo_desejado', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Em desenvolvimento', 'Em desenvolvimento'), ('Concluído', 'Concluído')], default='Novo', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
