# Generated by Django 6.1.1 on 2026-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('Sistema', 'Sistema'), ('Acesso', 'Acesso'), ('Equipamento', 'Equipamento'), ('Outros', 'Outros')], default='Sistema', max_length=100),
        ),
    ]
