# Generated by Django 6.1.1 on 2026-09-10 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chamado_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='area',
            field=models.CharField(blank=True, choices=[('Engenharia', 'Engenharia'), ('Producao', 'Produção'), ('Manutencao', 'Manutenção'), ('Qualidade', 'Qualidade'), ('Suprimentos', 'Suprimentos'), ('Administrativo', 'Administrativo'), ('TI', 'TI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='area_solicitante',
            field=models.CharField(choices=[('Engenharia', 'Engenharia'), ('Producao', 'Produção'), ('Manutencao', 'Manutenção'), ('Qualidade', 'Qualidade'), ('Suprimentos', 'Suprimentos'), ('Administrativo', 'Administrativo'), ('TI', 'TI')], max_length=50),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('colaborador', 'Colaborador'), ('gestor', 'Gestor de área'), ('gestor_ti', 'Gestor de TI')], default='colaborador', max_length=20)),
                ('area', models.CharField(blank=True, choices=[('Engenharia', 'Engenharia'), ('Producao', 'Produção'), ('Manutencao', 'Manutenção'), ('Qualidade', 'Qualidade'), ('Suprimentos', 'Suprimentos'), ('Administrativo', 'Administrativo'), ('TI', 'TI')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
