# Generated by Django 6.1.1 on 2026-09-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chamado_area_alter_projeto_area_solicitante_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='senha_temporaria',
            field=models.BooleanField(default=False),
        ),
    ]
