# Generated by Django 6.1.1 on 2026-09-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_senha_temporaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='papel',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('gestor', 'Gestor de área'), ('gestor_ti', 'Gestor de Desenvolvimento')], default='colaborador', max_length=20),
        ),
    ]
