# Generated by Django 6.1.1 on 2026-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfil_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='area',
            field=models.CharField(blank=True, choices=[('Engenharia', 'Engenharia'), ('Producao', 'Produção'), ('Manutencao', 'Manutenção'), ('Qualidade', 'Qualidade'), ('Suprimentos', 'Suprimentos'), ('Administrativo', 'Administrativo'), ('TI', 'TI')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em atendimento', 'Em atendimento'), ('Resolvido', 'Resolvido'), ('Cancelado', 'Cancelado')], db_index=True, default='Novo', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='usuario',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='area_solicitante',
            field=models.CharField(choices=[('Engenharia', 'Engenharia'), ('Producao', 'Produção'), ('Manutencao', 'Manutenção'), ('Qualidade', 'Qualidade'), ('Suprimentos', 'Suprimentos'), ('Administrativo', 'Administrativo'), ('TI', 'TI')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Em desenvolvimento', 'Em desenvolvimento'), ('Concluído', 'Concluído')], db_index=True, default='Novo', max_length=30),
        ),
    ]
