# Generated by Django 6.1.1 on 2026-09-10 10:23

import uuid
from django.db import migrations, models


def gerar_codigos_unicos(apps, schema_editor):
    Projeto = apps.get_model('core', 'Projeto')
    for projeto in Projeto.objects.all():
        projeto.codigo = uuid.uuid4()
        projeto.save(update_fields=['codigo'])


def reverter_codigos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projeto_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='codigo',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(gerar_codigos_unicos, reverter_codigos),
        migrations.AlterField(
            model_name='projeto',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
